name: Unit Testing for REST API Wrapper
run-name: Unit Testing for REST API Wrapper
on: [push]
jobs:
  Unit-Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '3.6.3' # The R version to download (if necessary) and use.

      - name: Unit Testing
        #run: Rscript install_dependencies.R
        run: R -e 'library('testthat'); test_dir("./unittesting", reporter=c("minimal", "location"))'
