name: Unit Testing for REST API Wrapper
run-name: Unit Testing for REST API Wrapper
on: [push]
jobs:
  Unit-Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '3.6.3' # The R version to download (if necessary) and use.

      #- uses: r-lib/actions/setup-r-dependencies@v2
      #  with:
      #    extra-packages: any::testthat

      - name: Install R dependencies
        run: Rscript install_dependencies.R
        
      - name: Unit Testing
        run: R -e 'library("testthat"); test_dir("./unittesting", reporter=c())'
